// festivals
export const SET_CREATE_FESTIVAL = 'SET_CREATE_FESTIVAL'
export const SET_LOADED_FESTIVALS = 'SET_LOADED_FESTIVALS'
export const SET_LOADED_MORE_FESTIVALS = 'SET_LOADED_MORE_FESTIVALS'

// articles
export const SET_CREATE_ARTICLE = 'SET_CREATE_ARTICLE'
export const SET_LOADED_ARTICLES = 'SET_LOADED_ARTICLES'
export const SET_LOADED_MORE_ARTICLES = 'SET_LOADED_MORE_ARTICLES'

// set random documents for festivals and articles
export const SET_RANDOOM_DOCUMENTS = 'SET_RANDOOM_DOCUMENTS'

// user
export const SET_USER = 'SET_USER'
export const SET_LOADED_USER_FESTIVALS = 'SET_LOADED_USER_FESTIVALS'
export const SET_LOADED_USER_ARTICLES = 'SET_LOADED_USER_ARTICLES'

// loading
export const SET_LOADING = 'SET_LOADING'
export const SET_FESTIVALS_LOADING = 'SET_FESTIVALS_LOADING'
export const SET_ARTICLES_LOADING = 'SET_ARTICLES_LOADING'

// errors
export const SET_CLEAR_ERROR = 'SET_CLEAR_ERROR'
export const SET_ERROR = 'SET_ERROR'

// search bar
export const SET_SEARCH_BAR = 'SET_SEARCH_BAR'
